services:

  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pSangam4251"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    image: ecommerce-app:latest
    container_name: ecommerce-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

volumes:
  mysql_data:
